# Generated by Django 3.2.5 on 2021-12-09 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberTournamentRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs.membership')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs.tournament')),
            ],
            options={
                'ordering': ['tournament'],
            },
        ),
        migrations.CreateModel(
            name='StageInterface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_num', models.IntegerField(default=1)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs.tournament')),
            ],
            options={
                'ordering': ['tournament'],
            },
        ),
        migrations.CreateModel(
            name='GroupStage',
            fields=[
                ('stageinterface_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='clubs.stageinterface')),
            ],
            bases=('clubs.stageinterface',),
        ),
        migrations.CreateModel(
            name='KnockoutStage',
            fields=[
                ('stageinterface_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='clubs.stageinterface')),
            ],
            bases=('clubs.stageinterface',),
        ),
        migrations.CreateModel(
            name='Organiser',
            fields=[
                ('membertournamentrelationship_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='clubs.membertournamentrelationship')),
                ('is_lead_organiser', models.BooleanField(default=False)),
            ],
            bases=('clubs.membertournamentrelationship',),
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('membertournamentrelationship_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='clubs.membertournamentrelationship')),
                ('round_eliminated', models.IntegerField(default=-1)),
            ],
            bases=('clubs.membertournamentrelationship',),
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.IntegerField(blank=True, choices=[(1, 'White Victory'), (2, 'Black Victory'), (3, 'Stalemate')], default=None)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs.stageinterface')),
            ],
            options={
                'ordering': ['stage'],
            },
        ),
        migrations.CreateModel(
            name='SingleGroup',
            fields=[
                ('stageinterface_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='clubs.stageinterface')),
                ('winners_required', models.IntegerField(default=1)),
                ('group_stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs.groupstage')),
            ],
            bases=('clubs.stageinterface',),
        ),
        migrations.AddConstraint(
            model_name='membertournamentrelationship',
            constraint=models.UniqueConstraint(fields=('member', 'tournament'), name='one_object_per_relationship'),
        ),
        migrations.AddField(
            model_name='match',
            name='black_player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='black', to='clubs.participant'),
        ),
        migrations.AddField(
            model_name='match',
            name='white_player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='white', to='clubs.participant'),
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.UniqueConstraint(fields=('white_player', 'black_player'), name='cannot_play_self'),
        ),
    ]
