# Generated by Django 3.2.5 on 2021-12-10 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['collection']},
        ),
        migrations.RenameField(
            model_name='match',
            old_name='group',
            new_name='collection',
        ),
    ]
