# Generated by Django 3.2.5 on 2021-11-14 17:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=48, validators=[django.core.validators.RegexValidator(regex='^[a-zA-Z]{1,}$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=48, validators=[django.core.validators.RegexValidator(regex='^[a-zA-Z]{1,}$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=32, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\w{3,}$')]),
        ),
    ]
