# Generated by Django 3.2.5 on 2021-12-13 06:07

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='match',
            name='cannot_play_self',
        ),
        migrations.AlterField(
            model_name='tournament',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.CheckConstraint(check=models.Q(('white_player', django.db.models.expressions.F('black_player')), _negated=True), name='cannot_play_self'),
        ),
        migrations.AddConstraint(
            model_name='tournament',
            constraint=models.UniqueConstraint(fields=('club', 'name'), name='tournament_name_must_be_unique_by_club'),
        ),
    ]
