# Generated by Django 3.2.5 on 2021-12-13 14:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_auto_20211213_0607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='capacity',
            field=models.PositiveIntegerField(choices=[(2, '2'), (4, '4'), (8, '8'), (16, '16'), (32, '32'), (48, '48'), (96, '96')], default=2, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(96)]),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='deadline',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='end',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='start',
            field=models.DateTimeField(),
        ),
    ]
