# Generated by Django 3.2.5 on 2021-11-16 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_club'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='owner',
        ),
    ]
