# Generated by Django 3.2.5 on 2021-11-18 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0005_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='description',
            field=models.CharField(max_length=280),
        ),
        migrations.AlterField(
            model_name='club',
            name='location',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='club',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
