# Generated by Django 3.2.5 on 2021-11-19 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0006_auto_20211118_1447'),
        ('clubs', '0006_auto_20211118_1504'),
    ]

    operations = [
    ]
