# Generated by Django 3.2.5 on 2021-11-19 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0007_merge_0006_auto_20211118_1447_0006_auto_20211118_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='experience',
            field=models.IntegerField(choices=[(1, 'Beginner'), (2, 'Intermediate'), (3, 'Advanced')], default=1),
        ),
        migrations.AddField(
            model_name='application',
            name='personalStatement',
            field=models.CharField(default='exit', max_length=580),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='member',
            name='isOwner',
            field=models.BooleanField(default=False),
        ),
    ]
