# Generated by Django 3.2.5 on 2021-11-19 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0008_auto_20211119_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='personalStatement',
            field=models.CharField(default='', max_length=580),
        ),
    ]
