# Generated by Django 3.2.5 on 2021-11-23 17:03


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0009_alter_application_personalstatement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['club']},
        ),
    ]
