# Generated by Django 3.2.5 on 2021-11-28 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0010_alter_member_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='personalStatement',
            new_name='personal_statement',
        ),
    ]
