# Generated by Django 3.2.5 on 2021-11-28 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0011_rename_personalstatement_application_personal_statement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='isOfficer',
            new_name='is_officer',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='isOwner',
            new_name='is_owner',
        ),
    ]
