# Generated by Django 3.2.5 on 2021-12-01 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0013_user_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='experience',
        ),
        migrations.AddField(
            model_name='user',
            name='experience',
            field=models.IntegerField(choices=[(1, 'Beginner'), (2, 'Intermediate'), (3, 'Advanced')], default=1),
        ),
    ]
