# Generated by Django 3.2.5 on 2021-12-02 14:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0014_auto_20211201_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=48, validators=[django.core.validators.RegexValidator(regex="^[a-zA-Z\\'\\-]{1,}$")]),
        ),
    ]
