# Generated by Django 3.2.5 on 2021-12-02 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0014_auto_20211201_1025'),
        ('clubs', '0014_ban'),
    ]

    operations = [
    ]
