# Generated by Django 3.2.5 on 2021-12-02 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0015_alter_user_last_name'),
        ('clubs', '0015_merge_0014_auto_20211201_1025_0014_ban'),
    ]

    operations = [
    ]
