# Generated by Django 3.2.5 on 2021-12-06 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0016_merge_20211202_1510'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Member',
            new_name='Membership',
        ),
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['club']},
        ),
        migrations.AlterModelOptions(
            name='ban',
            options={'ordering': ['club']},
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.UniqueConstraint(fields=('club', 'user'), name='application_to_club_unique'),
        ),
        migrations.AddConstraint(
            model_name='ban',
            constraint=models.UniqueConstraint(fields=('club', 'user'), name='user_ban_from_club_unique'),
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.UniqueConstraint(fields=('club', 'user'), name='user_in_club_unique'),
        ),
    ]
