# Generated by Django 3.2.5 on 2021-12-06 22:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0017_auto_20211206_1621'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(max_length=280)),
                ('capacity', models.PositiveIntegerField(default=16, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.MaxLengthValidator(96)])),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
    ]
