# Generated by Django 3.2.5 on 2021-12-07 11:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0019_auto_20211207_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 7, 11, 56, 51, 18792)),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 7, 11, 56, 51, 18774)),
        ),
    ]
