# Generated by Django 3.2.5 on 2021-12-07 11:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0020_auto_20211207_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='end',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='start',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
